#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run the install script with sudo."
  exit
fi

username=$(id -u -n 1000)
builddir=/home/$username/.dwm/
oscheck=$(lsb_release -is)

if [[ $oscheck == "Arch" ]] 
then
        # Printing distro check
	echo "################ Detected distro: $oscheck ################"

        # Dependency installation
        pacman -Syyu picom lxappearance polkit-gnome volumeicon dunst feh pcmanfm alacritty rofi dmenu xorg-xinit xorg unzip zip flameshot wget ttf-roboto --noconfirm

        # Download Nordic Theme
        cd $builddir
        bash ./scripts/gtk-theme

        # Installing fonts
        cd $builddir
        bash ./scripts/fonts

        # Installing cursor theme
        cd $builddir
        bash ./scripts/cursor

        # Copying GTK folder
        mkdir -p /home/$username/.config/
        cd $builddir/gtk-themes
        cp -r gtk-3.0 /home/$username/.config/

        # Compiling
        cd $builddir
        make clean install

        # Adding dwm to .xinitrc
        echo "exec dwm" >> /home/$username/.xinitrc

        # Confirm that we're done
        echo "dwm-mko has been installed on your Arch!"
        echo "Please run startx to launch into dwm."


elif [[ $oscheck == "Debian" ]]
then
        # Printing distro check
        echo "Detected distro: $oscheck"

        # Dependency installation
        apt install nala -y
        
        echo "Nala has been installed! (thank me later)"
        nala install picom lxappearance policykit-1-gnome volumeicon-alsa feh dunst pcmanfm alacritty suckless-tools rofi make gcc libx11-dev libxft-dev libxinerama-dev xorg unzip zip fonts-roboto flameshot -y
        
        # Download Nordic Theme
        mkdir -p /home/$username/.local/themes/
        cd /home/$username/.local/themes/
        git clone https://github.com/EliverLara/Nordic.git

        # Installing fonts
        cd $builddir
        bash ./scripts/fonts

        # Installing cursor theme
        cd $builddir
        bash ./scripts/cursor

        # Copying GTK folder
        mkdir -p /home/$username/.config/
        cd $builddir/gtk-themes
        cp -r gtk-3.0 /home/$username/.config/

        # Compiling
        cd $builddir
        make clean install

        # Adding dwm to .xinitrc
        echo "exec dwm" >> /home/$username/.xinitrc

        # Confirm that we're done
        echo "dwm-mko has been installed on Debian!"
        echo "Please run startx to launch into dwm."
else
        echo "Distro currently not supported, please make a PR/issue on github"
fi

## FEDORA SUPPORT COMING IN THE FUTURE

# elif [[ $oscheck == "Fedora" ]]
# then
#         # Printing distro check
#         echo "Detected distro: $oscheck"
#         cd /home/$SUDO_USER/.dwm
#         sudo make clean install
