#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
  then echo "Please run the install script with sudo."
  exit
fi

oscheck="$(lsb_release -is)"

if [[ $oscheck == "Arch" ]] 
then
        # Printing distro check
	echo "Detected distro: $oscheck";
        # Dependency installation
        pacman -Syyu picom volumeicon dunst feh pcmanfm alacritty rofi dmenu xorg-xinit xorg unzip zip flameshot wget --noconfirm;
         # Installing fonts
        bash ./scripts/fonts;
        # Compiling
        make clean install;
        # Confirm that we're done
        echo "dwm-mko has been installed on your arch machine!";
elif [[ $oscheck == "Debian" ]]
then
        # Printing distro check
        echo "Detected distro: $oscheck";
        # Dependency installation
        apt install nala -y;
        echo "Nala has been installed! (thank me later)";
        nala install picom volumeicon-alsa feh dunst pcmanfm alacritty suckless-tools rofi make gcc libx11-dev libxft-dev libxinerama-dev xorg unzip zip flameshot -y;
        # Installing fonts
        bash ./scripts/fonts;
        # Compiling
        make clean install;
        # Confirm that we're done
        echo "dwm-mko has been installed on your debian machine!";
else
        echo "Distro currently not supported, please make a PR/issue on github"
fi

## FEDORA SUPPORT COMING IN THE FUTURE

# elif [[ $oscheck == "Fedora" ]]
# then
#         # Printing distro check
#         echo "Detected distro: $oscheck";
#         cd /home/$SUDO_USER/.dwm;
#         sudo make clean install;
