#!/usr/bin/env bash

oscheck="$(lsb_release -is)"

if [[ $oscheck == "Arch" ]] 
then
	kernel() {
            echo -e " $(uname -r | sed s/1-1-zen//g)"
        }
elif [[ $oscheck == "Debian" ]]
then
        kernel() {
            echo -e " $(uname -r | sed s/-amd64//g)"
        }
fi

get_datetime() {
    date +"|   %a %d %b %Y |   %I:%M %p"
}

get_status() {
    echo "$(kernel) $(get_datetime)";
}

while true
do
    xsetroot -name "$(get_status)";
    sleep 1m;
done
